basket/urls.py
"""
package: basket
description: urls
"""
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('add_goods', views.BasketItemCreateView.as_view(), name='add-goods'),
    path('detail/<uuid:pk>', views.BasketDetailView.as_view(), name='basket-detail'),
    path('delete/<uuid:pk>', views.BasketItemDeleteView.as_view(), name='delete-item'),
    path('add_good_to_pay/<slug:slug>', views.GoodsToPayCreate.as_view(), name='add-goods-to-pay'),
]

clients/urls.py
"""
package: clients
description: urls
"""
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('registration', views.PhoneVerificationView.as_view(), name='registration-contacts'),
    path('registration/<slug:slug>', views.RegisterView.as_view(), name='registration'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('profile/<uuid:pk>', views.ClientDetailView.as_view(), name='profile'),
]

goods/urls.py
from django.urls import path
from . import views


app_name = 'goods'

urlpatterns = [
    path('goods/detail/<uuid:pk>', views.GoodDetailView.as_view(), name='good-detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tm_site.urls', namespace='tm_site')),
    path('admin/', admin.site.urls),
    path('auth/', include('clients.urls', namespace='clients')),
    path('goods/', include('goods.urls', namespace='goods')),
    path('basket/', include('basket.urls', namespace='basket'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

clients/models.py
"""
package: clients
description: models
"""
from uuid import uuid4
from django.db import models
from django.contrib.auth.models import User, Group
from django.core.exceptions import ObjectDoesNotExist
from pytils.translit import slugify  # для перевода кирилицы
from marketing.models import BonusCard
from basket.models import Basket
from goods.models import Good

class Contacts(models.Model):
    """
    модель для контактных данных клиента
    """
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        verbose_name='идентификатор')
    phone_number1 = models.CharField(
        max_length=50,
        unique=True,
        verbose_name='Номер телефона')
    phone_number2 = models.CharField(
        max_length=50,
        blank=True,
        verbose_name='Запасной номер')
    email = models.CharField(
        max_length=100,
        verbose_name='Адрес электронной почты')
    slug = models.SlugField(
        max_length=200,
        editable=False,
        verbose_name='ЧПУ')

    def __str__(self):
        return f'{self.phone_number1} {self.email}'

    def save(self, *args, **kwargs):  # pylint: disable=arguments-differ
        self.slug = slugify(f'{self.phone_number1}')
        super(Contacts, self).save(*args, **kwargs)

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'phone_number1': self.phone_number1,
            'phone_number2': self.phone_number2,
            'email': self.email,
        }

    class Meta:
        unique_together = ['phone_number1', 'email']
        verbose_name = 'контакт'
        verbose_name_plural = 'контакты'


class PersonalData(models.Model):
    """
    Модель для личных данных клиента
    """
    uuid = models.UUIDField(
        primary_key=True,
        default=uuid4,
        verbose_name='идентификатор')
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=100, verbose_name='Отчество')
    photo = models.ImageField(blank=True, upload_to='profile-picture', default="girl.jpg", verbose_name='фото профиля')
    
    def __str__(self):
        return f'{self.first_name} {self.last_name} {self.middle_name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'first_name': self.first_name,
            'last_name': self.last_name,
            'middle_name': self.middle_name,
        }

    class Meta:
        verbose_name = 'Личные данные'
        verbose_name_plural = 'личные данные'


def default_bonus_card():
    try:
        return BonusCard.objects.get(name='Member')
    except:
        return None


class UserProfile(models.Model):
    """
    модель для данных пользователя
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='Пользователь')
    bonus_card = models.OneToOneField(
        BonusCard,
        on_delete=models.SET_DEFAULT,
        default=default_bonus_card,
        blank=True,
        null=True,
        verbose_name='бонусная карта')
    basket = models.OneToOneField(
        Basket,
        on_delete=models.PROTECT,
        related_name='user_profile',
        verbose_name='корзина')
    contacts = models.ForeignKey(
        Contacts,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='контакты')
    personal_data = models.ForeignKey(
        PersonalData,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='личные данные')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='группа')
    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return f'{self.user.username}{self.uuid}'

    def to_dict(self):
        if self.bonus_card:
            return {
                'uuid': str(self.uuid),
                'user': self.user.username,
                'bonus_card': str(self.bonus_card.uuid),
                'contacts': str(self.contacts.uuid),
                'personal_data': str(self.personal_data.uuid),
                'basket': str(self.basket.uuid),
                'group': self.group.name
            }
        return {
            'uuid': str(self.uuid),
            'contacts': str(self.contacts.uuid),
            'personal_data': str(self.personal_data.uuid),
            'user': self.user.username,
            'basket': str(self.basket.uuid),
            'group': self.group.name
        }

    def save(self, *args, **kwargs):
        try:
            group = Group.objects.get(name='Клиенты')
            self.user.groups.add(group)
            self.group = group
        except ObjectDoesNotExist:
            pass
        super(UserProfile, self).save(*args, **kwargs)

clients/forms.py
"""
package: clients
description: forms
"""
from django import forms
from django.contrib.auth.models import User
from . import models


class PhoneNumberForm(forms.ModelForm):
    """
    форма для заполнения контактных данных
    """
    class Meta:
        model = models.Contacts
        fields = ['phone_number1', 'phone_number2', 'email']


class UserForm(forms.ModelForm):
    """
    форма для заполнения логина
    """
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {'password': forms.TextInput(attrs={'type': 'password'})}

class PersonalDataForm(forms.ModelForm):
    """
    форма для заполнения личных данных
    """
    class Meta:
        model = models.PersonalData
        fields = ['first_name', 'last_name', 'middle_name', 'photo']
        widgets = {
            'user': forms.HiddenInput()
        }

clients/views.py
"""
package: clients
description: views
"""
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from django.conf import settings
from modules import pass_gen
from . import models, forms, tasks as clients_tasks



class PhoneVerificationView(generic.CreateView):
    """
    представление для регистрации пользователя
    с указанием телефонного номера
    """
    form_class = forms.PhoneNumberForm
    template_name = 'clients/phone_verification.html'

    def get_success_url(self):
        return reverse('clients:registration',
                       kwargs={'slug': self.object.slug})


class RegisterView(generic.CreateView):
    """
    представление для продолжения регистрации, для
    указания данных пользователя
    """
    form_class = UserCreationForm
    template_name = 'clients/registration.html'

    def get_context_data(self, *args, **kwargs):  # pylint: disable=arguments-differ
        context = super(RegisterView, self).get_context_data(*args, **kwargs)
        context['personal_form'] = forms.PersonalDataForm
        return context

    def get_success_url(self, user):
        authenticate(username=user.username,
                     password=user.password)
        login(self.request, user)
        return reverse('tm_site:index')

    def form_valid(self, form):
        if form.is_valid():
            user = form.save()  # saving cleaned data into model
            personal = forms.PersonalDataForm(self.request.POST).save()  # saving cleaned data from
            # personal_data form into PersonalData model
            contacts = models.Contacts.objects.get(
                slug=self.kwargs.get('slug'))  # defining variable that is Contacts model instance
            user.profile.contacts, user.profile.personal_data = contacts, personal  # writing personal data and contacts
            # into user model
            user.profile.save()  # saving into user model
        return redirect(self.get_success_url(user))


class LoginView(generic.FormView):
    """
    представдение для авторизации
    """
    form_class = AuthenticationForm
    template_name = 'clients/login.html'

    def form_valid(self, form):
        user = form.get_user()
        login(self.request, user)
        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        return reverse('tm_site:index')


class LogoutView(generic.base.View):
    """
    представление для выхода из учетной записи
    """

    def get(self, request):
        """
        метод для логаута
        """
        logout(request)
        return HttpResponseRedirect(reverse('tm_site:index'))


@method_decorator(permission_required('clients.view_userprofile', login_url=settings.LOGIN_URL), name='dispatch')
@method_decorator(permission_required('clients.change_userprofile', login_url=settings.LOGIN_URL), name='dispatch')
class ClientDetailView(generic.DetailView):
    model = models.UserProfile
    template_name = 'clients/user_profile.html'

clients/templates/clients/goods_to_pay.html
{% extends 'base.html'%}

{% block content %}
{{form.errors}}
{{ form }}
{% endblock %}

clients/templates/clients/logged_out.html
{% extends "base.html" %}

{% block content %}
<p>Logged out!</p>


{% endblock %}

clients/templates/clients/login.html
{% extends 'registration_base.html'%}
{% load static i18n %}

{% block content %}

{% if form.errors %}
{% for key, value in form.errors.items %}
{{ value }}
{% endfor %}
{% endif %}

<form action="{% url 'clients:login' %}" method="POST">
	{% csrf_token %}
	<div class="form-group has-feedback">
		<input type="text" class="form-control" placeholder="Login" name="username">
		<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
	</div>

	<div class="form-group has-feedback">
		<input type="password" class="form-control" placeholder="Password" name="password">
		<span class="glyphicon glyphicon-lock form-control-feedback"></span>
	</div>

	<div class="row">
		<div class="col-xs-8">
			<div class="checkbox icheck">
				<label>
					<input type="checkbox"> Remember Me
				</label>
			</div>
		</div>
		<!-- /.col -->
		<div class="col-xs-4">
			<button type="submit" class="btn btn-default btn-block btn-flat">Sign In</button>
		</div>
		<!-- /.col -->
	</div>
</form>

<div class="social-auth-links text-center">
	<p>- OR -</p>
	<a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
		Facebook</a>
	<a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
		Google+</a>
</div>
<!-- /.social-auth-links -->

<a href="#">I forgot my password</a><br>
<a href="register.html" class="text-center">Register a new membership</a>

</div>
<!-- /.login-box-body -->
</div>
{% endblock %}

clients/templates/clients/phone_verification.html
{% extends 'registration_base.html' %}

{% block content %}
{% if form.errors %}
{% for key, value in form.errors.items %}
  <p>{{ value }}</p>
{% endfor %}
{% endif %}

<div class="login-box">
	<form method="post">
    	{% csrf_token %}
		<div class="col-xs-10">
    		<div class="form-group has-feedback">
				<input type="text" class="form-control" placeholder="Номер телефона" name="phone_number1">
	  	  		<span class="glyphicon glyphicon-phone form-control-feedback"></span>
			</div>
		</div>

		<div class="col-xs-10">
			<div class="form-group has-feedback">
	  			<input type="text" class="form-control" placeholder="Запасной номер телефона" name="phone_number2">
				<span class="glyphicon glyphicon-phone form-control-feedback"></span>
			</div>
		</div>

		<div class="col-xs-10">
			<div class="form-group has-feedback">
				<input type="text" class="form-control" placeholder="Адрес почты" name="email">
				<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-6"></div>
			<div class="col-xs-4">
				<button type="submit" class="btn btn-default btn-block btn-flat">Дальше</button>
			</div>
	    	<!-- /.col -->
	  	</div>
	</form>
</div>
{% endblock %}

clients/templates/clients/registration.html
{% extends 'registration_base.html'%}

{% block content %}

{% if form.errors %}
{% for key, value in form.errors.items %}
<p>{{ value }}</p>
{% endfor %}
{% endif %}


{% if next %}
{% if user.is_authenticated %}
<p>Your account doesn't have access to this page. To proceed,
  please login with an account that has access.</p>
{% else %}
<p>Please login to see this page.</p>
{% endif %}
{% endif %}

<form method="post">
  {% csrf_token %}
  {% for field in form %}
  <div class="form-group has-feedback">
    {% if field.name != 'username' %}
    <input type="password" class="form-control" placeholder="{{field.label}}" name="{{field.name}}">
    {% else %}
    <input type="text" class="form-control" placeholder="{{field.label}}" name="{{field.name}}">
    {% endif %}
    <span class="glyphicon glyphicon form-control-feedback"></span>
  </div>
  {% endfor %}
  {% for field in personal_form %}
  <div class="form-group has-feedback">
    {% if field.name == 'photo' %}
    <input type="file" class="form-control" placeholder="{{field.label}}" name="{{field.name}}" accept="image/*">
    {% else %}
    <input type="text" class="form-control" placeholder="{{field.label}}" name="{{field.name}}">
    {% endif %}
    <span class="glyphicon glyphicon form-control-feedback"></span>
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-xs-8"></div>
    <div class="col-xs-4">
      <button type="submit" class="btn btn-default btn-block btn-flat">Дальше</button>
    </div>
    <!-- /.col -->
  </div>
</form>
{% endblock %}

clients/templates/clients/user_profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<!-- Main content -->
<section class="content">

    <div class="row">
        <div class="col-md-3">

            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    {% thumbnail object.personal_data.photo "200x200" crop="center" as im %}
                    <img class="profile-user-img img-responsive img-circle" src="{{im.url}}">
                    {% endthumbnail %}
                    <h3 class="profile-username text-center">{{object.user.username}}</h3>

                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item">
                            <b>Followers</b> <a class="pull-right">1,322</a>
                        </li>
                        <li class="list-group-item">
                            <b>Following</b> <a class="pull-right">543</a>
                        </li>
                        <li class="list-group-item">
                            <b>Friends</b> <a class="pull-right">13,287</a>
                        </li>
                    </ul>

                    <a href="#" class="btn btn-primary btn-block"><b>Follow</b></a>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

            <!-- About Me Box -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">About Me</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <strong><i class="fa fa-book margin-r-5"></i> Education</strong>

                    <p class="text-muted">
                        B.S. in Computer Science from the University of Tennessee at Knoxville
                    </p>

                    <hr>

                    <strong><i class="fa fa-map-marker margin-r-5"></i> Location</strong>

                    <p class="text-muted">Malibu, California</p>

                    <hr>

                    <strong><i class="fa fa-pencil margin-r-5"></i> Skills</strong>

                    <p>
                        <span class="label label-danger">UI Design</span>
                        <span class="label label-success">Coding</span>
                        <span class="label label-info">Javascript</span>
                        <span class="label label-warning">PHP</span>
                        <span class="label label-primary">Node.js</span>
                    </p>

                    <hr>

                    <strong><i class="fa fa-file-text-o margin-r-5"></i> Notes</strong>

                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam fermentum enim neque.</p>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#goods_to_pay" data-toggle="tab">Приобретено</a></li>
                    <li><a href="#basket" data-toggle="tab">Корзина</a></li>
                    <li><a href="#settings" data-toggle="tab">Настройки</a></li>
                </ul>
                <div class="tab-content">
                    <div class="active tab-pane" id="goods_to_pay">
                        {% for item in object.user.user_goodstopay.all %}
                        <ul class="list-group">
                            <li>{{ item }}</li>
                        </ul>
                        {% endfor %}
                    </div>
                    <!-- /.tab-pane -->
                    <div class="tab-pane" id="basket">
                        <!-- The timeline -->
                        {% for item in object.basket.basket_basketitem.all %}
                        <table class="table table-boardered">
                            <thead>
                            <tr>
                                <th>Товар</th>
                                <th>Количество</th>
                                <th>Цена</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>{{ item.good }}</td>
                                <td>{{ item.number }}</td>
                                <td>{{ item.price }}</td>
                                <td>
                                    <form method="POST" action="{% url 'clients:add-goods-to-pay' item.good.slug %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="basket_item" value="{{item.uuid}}">
                                        <input type="hidden" name="good" value="{{ item.good.uuid }}">
                                        <input type="hidden" name="user" value="{{ object.user_id }}">
                                        <input type="hidden" name="number" value="{{ item.number }}">
                                        <button type="submit" class="btn btn-default">Приобрести</button>
                                    </form>
                                    <form method="POST" action="{% url 'basket:delete-item' item.uuid %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="good" value="{{ item.good }}">
                                        <input type="hidden" name="number" value="{{ item.number }}">
                                        <input type="hidden" name="basket" value="{{ object }}">
                                        <button class="btn btn-danger">Удалить</button>
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                        {% endfor %}
                    </div>
                    <!-- /.tab-pane -->

                    <div class="tab-pane" id="settings">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <label for="inputName" class="col-sm-2 control-label">Name</label>

                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="inputName" placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                                <div class="col-sm-10">
                                    <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputName" class="col-sm-2 control-label">Name</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputName" placeholder="Name">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputExperience" class="col-sm-2 control-label">Experience</label>

                                <div class="col-sm-10">
                                    <textarea class="form-control" id="inputExperience" placeholder="Experience"></textarea>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputSkills" class="col-sm-2 control-label">Skills</label>

                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="inputSkills" placeholder="Skills">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox"> I agree to the <a href="#">terms and conditions</a>
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-danger">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->

</section>
<!-- /.content -->
</div>
{% endblock %}