basket/urls.py
"""
package: basket
description: urls
"""
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('add_goods', views.BasketItemCreateView.as_view(), name='add-goods'),
    path('detail/<uuid:pk>', views.BasketDetailView.as_view(), name='basket-detail'),
    path('delete/<uuid:pk>', views.BasketItemDeleteView.as_view(), name='delete-item'),
    path('add_good_to_pay/<slug:slug>', views.GoodsToPayCreate.as_view(), name='add-goods-to-pay'),
]

clients/urls.py
"""
package: clients
description: urls
"""
from django.urls import path
from . import views

app_name = 'clients'

urlpatterns = [
    path('registration', views.PhoneVerificationView.as_view(), name='registration-contacts'),
    path('registration/<slug:slug>', views.RegisterView.as_view(), name='registration'),
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    path('profile/<uuid:pk>', views.ClientDetailView.as_view(), name='profile'),
]

goods/urls.py
from django.urls import path
from . import views


app_name = 'goods'

urlpatterns = [
    path('goods/detail/<uuid:pk>', views.GoodDetailView.as_view(), name='good-detail')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('tm_site.urls', namespace='tm_site')),
    path('admin/', admin.site.urls),
    path('auth/', include('clients.urls', namespace='clients')),
    path('goods/', include('goods.urls', namespace='goods')),
    path('basket/', include('basket.urls', namespace='basket'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tm_site/urls.py
"""
package: tm_site
description: urls
"""
from django.urls import path, include
from . import views

app_name = 'tm_site'

urlpatterns = [
    path('', views.MainPageView.as_view(), name='index')
]

goods/models.py
"""
Module models
"""
from uuid import uuid4
from django.db import models
from django.urls import reverse
from pytils.translit import slugify
from stores import models as store_models


class Categories(models.Model):
    """
    Model Categories
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.CharField(max_length=100, unique=True, verbose_name="Название Родительской категории")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    class Meta:
        verbose_name = 'Родительскую Категорию'
        verbose_name_plural = 'Родительская Категория'

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'name': self.name,
        }


class Category(models.Model):
    """
    Model Category
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    parent = models.ForeignKey(
        Categories,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        verbose_name="Родительская категория"
    )
    name = models.CharField(max_length=100, unique=True, verbose_name="Название категории")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'parent': str(self.parent.uuid),
            'name': self.name
        }

    class Meta:
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категория'


class GoodName(models.Model):
    """
    Model GoodName
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.CharField(max_length=100, verbose_name="Название Товара")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'name': self.name
        }

    class Meta:
        verbose_name = 'Название Товара'
        verbose_name_plural = 'Название Товара'


class Good(models.Model):
    """
    Model Good
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    store = models.ForeignKey(store_models.Store, blank=True, null=True, on_delete=models.CASCADE, verbose_name="Склад")
    name = models.ForeignKey(GoodName, on_delete=models.CASCADE, verbose_name="Название Товара")
    photo = models.ImageField(blank=True, upload_to='good-photo', default='girl.jpg', verbose_name='Фото товара')
    model = models.CharField(max_length=200, verbose_name="Модель")
    total_price = models.DecimalField(
        max_digits=50,
        decimal_places=2,
        verbose_name='Общая цена'
    )
    credit_time = models.PositiveIntegerField(
        default=12,
        verbose_name='Время кредита'
    )
    has_prepayment = models.BooleanField(
        default=True, verbose_name="Есть предоплата"
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        verbose_name="Категория Товара"
    )
    in_stock = models.BooleanField(
        default=False,
        verbose_name="В наличии"
    )
    slug = models.SlugField(
        max_length=250,
        editable=False,
        db_index=True,
        blank=True,
        verbose_name='ЧПУ'
    )
    description = models.TextField(
        max_length=500,
        null=True,
        blank=True,
        verbose_name="Описание товара"
    )
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        verbose_name='Дата добавления'
    )
    edited = models.DateTimeField(
        auto_now=True,
        editable=False,
        verbose_name='Дата редактирования'
    )

    def get_absolute_url(self):
        """
        Function returns url
        """
        return reverse('goods:good-detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'{self.name.name}, {self.model}'

    def save(self, *args, **kwargs):  # pylint: disable=arguments-differ
        self.slug = slugify(f'{self.name.name}')
        super(Good, self).save(*args, **kwargs)

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'store': str(self.store.uuid),
            'name': str(self.name.uuid),
            'model': self.model,
            'total_price': str(self.total_price),
            'credit_time': self.credit_time,
            'has_prepayment': self.has_prepayment,
            'category': str(self.category.uuid),
            'in_stock': self.in_stock,
            'description': self.description
        }

    class Meta:
        unique_together = ['name', 'model', 'category']
        verbose_name = 'Партия товара'
        verbose_name_plural = 'Партии товара'


class SpecificationName(models.Model):
    """
    Model SpecificationName
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.CharField(max_length=250, unique=True, blank=True, verbose_name="Название характеристики")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'name': self.name
        }

    class Meta:
        verbose_name = 'Название Спецификации для Текстовых'
        verbose_name_plural = 'Название Спецификации для Текстовых'


class SpecificationNameBool(models.Model):
    """
    Model SpecificationNameBool
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.CharField(max_length=250, unique=True, blank=True, null=True, verbose_name="Название характеристики")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.name}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'name': self.name
        }

    class Meta:
        verbose_name = 'Название Спецификации для Булево'
        verbose_name_plural = 'Название Спецификации для Булево'


class SpecificationValue(models.Model):
    """
    Model SpecificationValue
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    value = models.CharField(max_length=250, unique=True, blank=True, verbose_name="Значение характеристики")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.value}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'value': self.value
        }

    class Meta:
        verbose_name = 'Значение Спецификации'
        verbose_name_plural = 'Значение Спецификации'


class Specification(models.Model):
    """
    Model Specification
    """
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.ForeignKey(SpecificationName, on_delete=models.CASCADE, verbose_name="Название характеристики")
    value = models.ForeignKey(SpecificationValue, on_delete=models.CASCADE, verbose_name="Значение характеристики")
    good = models.ForeignKey(Good, on_delete=models.CASCADE, related_name='spec', verbose_name="Название товара")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')
    edited = models.DateTimeField(auto_now=True, editable=False, verbose_name='Дата редактирования')

    def __str__(self):
        return f'{self.name.name}, {self.value.value}'

    def to_dict(self):
        """
        returns dict
        """
        return {
            'uuid': str(self.uuid),
            'name': str(self.name.uuid),
            'value': str(self.value.uuid),
            'good': str(self.good.uuid)
        }

    class Meta:
        verbose_name = 'Спецификацию'
        verbose_name_plural = 'Спецификация'


class SpecificationBool(models.Model):
    """
    Model SpecificationBool
    """
    CHOICES = (
        ('Нет', 'Нет'),
        ('Есть', 'Есть'),
        )
    uuid = models.UUIDField(primary_key=True, default=uuid4, verbose_name='идентификатор')
    name = models.ForeignKey(SpecificationNameBool, on_delete=models.CASCADE, blank=True, verbose_name="Название характеристики")
    value = models.CharField(max_length=250, default=False, blank=True, null=True, choices=CHOICES, verbose_name="Значение характеристики")
    good = models.ForeignKey(Good, on_delete=models.CASCADE, related_name='spec_bool', verbose_name="Название товара")
    created = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата добавления')

templates/index.html
{% extends "base.html" %}
{% load i18n thumbnail %}

{% block content %}
<section class="content">
	<div class="col-md-12">
		<div class="box">
			<div class="box-header">
				<ul>
					{% if user.is_authenticated %}
					<p><h2>Здравствуйте, {{user.profile.personal_data.first_name}}!</h2></p>
					{% else %}
					<p><h2>Вы не авторизованы</h2></p>
					{% endif %}
				</ul>
				<ul>
					{% if user.is_authenticated and user.username != 'admin' %}
					<a class="btn btn-default" href="{% url 'clients:profile' user.profile.uuid %}">
						Профиль
						<span class="glyphicon glyphicon-user"></span>
					</a>
					<a class="btn btn-default" href="{% url 'basket:basket-detail' user.profile.basket_id %}">
						Корзина
						<span class="glyphicon glyphicon-shopping-cart"></span>
					</a>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>

	<div class="col-md-12">
		<div class="box">
			<div class="box-header">
				<h3 class="box-title">Недавно добавлено</h3>
			</div>
			<div class="box-body">
				<div class="panel">
					<div class="content">
						<div class="row">
							{% for good in goods %}
							<div class="col-md-3">
								<div class="small-box responsive" style="color:gray">
									<ul class="products-list product-list-in-box">
										<div class="col-md-1">
											<div class="product-img">
												{% thumbnail good.photo "400x400" crop="center" as im %}
												<img src="{{ im.url }}" alt="Product Image">
												{% endthumbnail %}
											</div>
										</div>
										<div class="col-md-1">
											<div class="product-info">
												<a href="{% url 'goods:good-detail' good.uuid %}" style="color: #525252" class="product-title">{{ good.name }}
													<span class="label label-default">{{ good.total_price }} сум</span>
												</a>
												<form method="POST" action="{% url 'basket:add-goods' %}">
													{% csrf_token %}
													<input type="hidden" name="basket" id="id_basket" value="{{ user.profile.basket_id }}">
													<input type="hidden" name="good" id="id_good" value="{{ good.uuid }}">
													<div class="input-group">
														<input type="number" class="form-control" name="number" id="id_number" min="1" style="width: 5em" value=1>
													</div>
													<input type="submit" class="btn btn-default" value="В корзину">
												</form>
											</div>
										</div>
									</ul>
								</div>
							</div>
							{% endfor %}
						</div>
					</div>
				</div>
				<!-- /.item -->
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/left_menu.html
{% load i18n %}

<li class="active treeview">
  {% if perms.agency.view_agent %}
  <a href="#">
    <i class="fa fa-book"></i> <span>{% trans 'Hotel' %}</span>
    <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
  </a>
  <ul class="treeview-menu">
    <li><a href="{% url 'tm_site:index' %}"><i class="fa fa-circle-o"></i>Главная</a></li>
  </ul>
  {% endif %}
</li>

templates/registration_base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Texnomart | {% trans 'Log in' %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{% static '/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static '/bower_components/font-awesome/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static '/bower_components/Ionicons/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static '/dist/css/AdminLTE.min.css' %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static '/plugins/iCheck/square/blue.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

      <!-- Google Font -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>
  <body class="hold-transition login-page">
  <div class="login-box">
      <div class="login-logo">
		<a href="/"><b>F</b>Project</a>
      </div>
      <!-- /.login-logo -->
      <div class="login-box-body">
	<p class="login-box-msg">{% trans 'Sign in to start your session' %}</p>
  {% block content %}
  {% endblock %}

    <!-- /.login-box -->

    <!-- jQuery 3 -->
    <script src="{% static '/bower_components/jquery/dist/jquery.min.js' %}"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="{% static '/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- iCheck -->
    <script src="{% static '/plugins/iCheck/icheck.min.js' %}"></script>
    <script>
      $(function () {
      $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
      });
      });
    </script>
  </body>
</html>